/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.bukkit.plugin.java.JavaPlugin;

public class mcProxyPlugin extends JavaPlugin {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new mcProxyPlugin().getGreeting());
    }    @Override
    public void onEnable() {
        getLogger().info("mcProxyPlugin enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("mcProxyPlugin disabled!");
    }
}
