/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

public class mcProxyPlugin extends JavaPlugin {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new mcProxyPlugin().getGreeting());
    }

    @Override
    public void onEnable() {
        getLogger().info("mcProxyPlugin enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("mcProxyPlugin disabled!");
    }

    @Override
    public boolean onCommand(@NotNull CommandSender commandSender, @NotNull Command command, @NotNull String s,
            @NotNull String @NotNull [] strings) {
        if (!(commandSender instanceof Player player)) {
            return false;
        }
        return true;
    }

}
