/*
 * This source file was generated by the Gradle 'init' task
 */
package org.cf_t.mc;

import java.util.UUID;
import java.util.logging.Level;

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class mcProxyPlugin extends JavaPlugin implements Listener {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new mcProxyPlugin().getGreeting());
    }

    @Override
    public void onLoad() {
        getLogger().info("mcProxyPlugin loaded!");
    }

    @Override
    public void onEnable() {
        getLogger().info("mcProxyPlugin enabled!");
        getServer().getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        getLogger().info("mcProxyPlugin disabled!");
    }

    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {

        String name = event.getPlayer().getName();
        UUID uuid = event.getPlayer().getUniqueId();
        String ip = event.getPlayer().getAddress().toString();
        getLogger().log(Level.INFO, "Player: {0}", name);
        getLogger().log(Level.INFO, "UUID: {0}", uuid);
        getLogger().log(Level.INFO, "IP: {0}", ip);
    }

}
