/*
 * This source file was generated by the Gradle 'init' task
 */
package org.cf_t.mc;

import java.io.IOException;
import java.util.UUID;
import java.util.logging.Level;

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class mcProxyPlugin extends JavaPlugin implements Listener {

    private String pin = "";
    private String infoAddr = "";

    public static void main(String[] args) {
        System.out.println("this is paper plugin");
    }

    @Override
    public void onLoad() {
        getLogger().info("mcProxyPlugin loaded!");
    }

    @Override
    public void onEnable() {
        pin = getConfig().getString("settings.infoPin");
        infoAddr = getConfig().getString("settings.infoAddr");
        getLogger().log(Level.INFO, "pin:{0}", pin);
        getLogger().log(Level.INFO, "infoAddr:{0}", infoAddr);
        getLogger().info("mcProxyPlugin enabled!");
        getServer().getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        getLogger().info("mcProxyPlugin disabled!");
    }

    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {

        String name = event.getPlayer().getName();
        UUID uuid = event.getPlayer().getUniqueId();
        String ip = event.getPlayer().getAddress().toString();
        getLogger().log(Level.INFO, "Player: {0}", name);
        getLogger().log(Level.INFO, "UUID: {0}", uuid);
        getLogger().log(Level.INFO, "IP: {0}", ip);
        String url = String.format("http://%s?uuid=%s&pin=%s&quit=false", infoAddr, uuid.toString(), pin);
        try {
            String playerInfo = http.get(url);
            getLogger().log(Level.INFO, playerInfo);
        } catch (IOException | InterruptedException ex) {
            System.getLogger(mcProxyPlugin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    @EventHandler
    public void onPlayerQuit(PlayerQuitEvent event) {
        String name = event.getPlayer().getName();
        UUID uuid = event.getPlayer().getUniqueId();

        getLogger().log(Level.INFO, "Player quit: {0}", name);
        getLogger().log(Level.INFO, "UUID: {0}", uuid);
        String url = String.format("http://%s?uuid=%s&pin=%s&quit=true", infoAddr, uuid.toString(), pin);
        try {
            http.get(url);
        } catch (IOException | InterruptedException ex) {
            System.getLogger(mcProxyPlugin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

}
